import { test, expect, type Route } from '@playwright/test'
import { openDesignPage } from '../helpers'

// Extensions › Capabilities, in a real browser: Commerce turns on with one action. The confirmation names what it
// adds; start answers "continue", the page sends the continue itself, and the card ends on the
// summary the activation recorded, with the management view read before and after. The server's
// answers are inline (fixtures/ is generated by the builder fixture build).
const json = (route: Route, body: unknown) =>
  route.fulfill({ contentType: 'application/json', body: JSON.stringify(body) })

const commerce = (over: Record<string, unknown> = {}) => ({
  id: 'thallo.commerce',
  label: 'Commerce',
  description: 'Products, orders and checkout.',
  requires: [],
  owning_package: 'glueful/commerce',
  requested: false,
  available: true,
  reason: null,
  remedy: null,
  effective: false,
  management: 'activation',
  activation: null,
  application_files_writable: true,
  engine_enabled: true,
  // Commerce declares its own copy (CommerceIntegrationServiceProvider::capabilities()).
  copy: {
    turn_on:
      'This prepares your store and adds products, orders, shop blocks and templates. ' +
      'Your existing content is kept.',
    turn_off:
      "Commerce's pages, blocks and menu are hidden. Products, orders and your content " +
      'are kept, and you can turn it on again.',
    links: [
      { label: 'Products', to: '/commerce/products' },
      { label: 'Block types', to: '/settings/block-types' },
    ],
  },
  ...over,
})

const record = (over: Record<string, unknown> = {}) => ({
  capability: 'thallo.commerce',
  generation: 1,
  status: 'preparing',
  steps_done: ['mark_preparing', 'enable_engine'],
  next_step: 'verify_boot',
  failed_step: null,
  error: null,
  remedy: null,
  workspaces: {},
  result: { engine: 'already' },
  actor: 'proofs',
  updated_at: '2026-10-02 12:00:00',
  ...over,
})

const succeeded = record({
  status: 'succeeded',
  steps_done: [
    'mark_preparing',
    'enable_engine',
    'verify_boot',
    'seed_blocks',
    'grant_permissions',
    'finalize',
  ],
  next_step: null,
  result: {
    engine: 'already',
    cache_stale: false,
    blocks_created: 18,
    grants: { superuser: 4, administrator: 3 },
  },
})

const manage = (capabilities: unknown[]) => ({ success: true, data: { capabilities } })

test('turning on Commerce runs start, then continue, and shows what was added', async ({
  page,
}) => {
  await openDesignPage(page) // signs in
  const calls: string[] = []
  let finished = false
  await page.route('**/v1/admin/capabilities/manage', (route) => {
    calls.push('manage')
    return json(
      route,
      manage([
        finished
          ? commerce({ requested: true, effective: true, activation: succeeded })
          : commerce(),
      ]),
    )
  })
  await page.route('**/v1/admin/capabilities/thallo.commerce/activation', (route) => {
    calls.push('start')
    return json(route, { success: true, data: { activation: record(), continue: true } })
  })
  await page.route('**/v1/admin/capabilities/thallo.commerce/activation/continue', (route) => {
    calls.push(`continue:${(route.request().postDataJSON() as { generation: number }).generation}`)
    finished = true
    return json(route, { success: true, data: { activation: succeeded, continue: false } })
  })

  await page.goto('/admin/extensions')
  await expect(page.getByRole('heading', { name: 'Extensions' })).toBeVisible({ timeout: 20_000 })
  const card = page.locator('[data-test="capability-thallo.commerce"]')
  await expect(card).toBeVisible({ timeout: 20_000 })
  await card.getByRole('switch').click()

  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('Turn on Commerce?')
  await expect(dialog).toContainText('Your existing content is kept.')
  await page.locator('[data-test="capability-confirm-turn-on"]').click()

  await expect(card.locator('[data-test="capability-summary"]')).toContainText(
    'Commerce is on. Added 18 blocks and granted 7 new permissions.',
  )
  expect(calls.filter((c) => c !== 'manage')).toEqual(['start', 'continue:1'])
  expect(calls[0]).toBe('manage')
  await expect.poll(() => calls.lastIndexOf('manage')).toBeGreaterThan(calls.indexOf('continue:1'))
  await expect(card.getByRole('link', { name: 'Products' })).toBeVisible()
})
